spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.baseUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %highlight(%-5level) %red([%thread]) %magenta(%X{traceId:-}) %yellow(%logger{15}) - %msg%n}

keycloak:
  baseUrl: http://localhost:9090
  realm: ${KEYCLOAK_REALM}
  tokenUri: /realms/${keycloak.realm}/protocol/openid-connect/token
  userUri: /admin/realms/${keycloak.realm}/users
  roleUri: /admin/realms/${keycloak.realm}/roles
  clientUri: /admin/realms/${keycloak.realm}/clients
  clientId: ${KEYCLOAK_CLIENT_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 8081
