ALTER TABLE product
    ADD COLUMN created TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN changed_by VARCHAR(50),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE technical_details
    ADD COLUMN created TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN changed_by VARCHAR(50),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD COLUMN created TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN changed_by VARCHAR(50),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE inventories
    DROP COLUMN product_id;

ALTER TABLE inventories
    ADD COLUMN created TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN changed_by VARCHAR(50),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
